source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

# Exclude problematic versions of cocoapods and activesupport that causes build failures.
gem 'cocoapods', '>= 1.13', '!= 1.15.0', '!= 1.15.1'
gem 'activesupport', '>= 6.1.7.5', '!= 7.1.0'
gem 'xcodeproj', '< 1.26.0'
gem 'concurrent-ruby', '< 1.3.4'
# 系统 Ruby 2.6.10：钉住需要 Ruby 3.0+ 的传递依赖到兼容版本
gem 'ffi', '< 1.17.0'
gem 'securerandom', '< 0.4'
gem 'logger', '< 1.6'
